### ISSUE TITLE
Usar Jade como template engine.

### ISSUE THREAD

**Issue by russiann** [thompsonemerson/simple-app-angular#3]
E aee Thompson :) tudo bem? 
Uma dica, usa Jade como template engine. 
O código fica mais limpo, mais claro e mais fácil de manter.

**Comment by thompsonemerson** [comment]
Opa, Tudo bem!
Pode crê @Russian60 , uso jade em meus projetos,
é que nesse o objetivo maior é pegar o publico "leigo", e não queria perder o foco.
Mas valeu ai, e fica a vontade para colaborar, caso queira.
Abraço!
